### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lemkeb** [relayr/python-virtual-device#2]
This post is nicely written. The instructions are clear and easy to follow. Here's my feedback on what can be improved:

- Always use the following spelling for the company name, even at the beginning of a sentence: relayr
- developer.relayr.io is always referred to as the **Developer Dashboard**.
- Revise:
	-  "This document will allow you to virtually simulate . . . " -> "This post will show you how to create a virtual simulation of . . ."
	-  "through an intuitive GUI that looks like this:" -> "using an intuitive GUI:"
	-  "So first step is to get a representation of . . . " -> "The first step is to create a representation of . . ."
	-  "Through this entity we will manage sent/received data, MQTT credentials and UI interface of the relayr Dashboard." -> "This entity will allow you to manage sent/received device data and MQTT credentials through the UI of the Developer Dashboard."
	-  "to get more advanced feature" -> "in order to use more advanced features"
	-  Comma after "But for now"
	-  "Analog sensors, in our case a Luminosity sensor," -> "Analog sensors - in our case, a luminosity sensor - "
- This post could use a more compelling "why" statement at the beginning. Why should somebody do this? (i.e., what will they learn from this tutorial)
- Show where to get the credentials in the Dashboard.
- It might seem obvious, but you should tell the reader to clone the repository.
- "If you are able to see the Virtual Board" See it where? How? (Device activity in the dashboard?)

**Comment by camzeech** [comment]
Has been taken into account in latest Readme update
