### ISSUE TITLE
T

### ISSUE THREAD

**Issue by perusio** [relayr/python-virtual-device#5]
1. The `VirtualSensorsActuators.py`code needs to be profusely commented so that people can add to it. I know it's simple but the idea is for this to be a seed for people to develop it.
2. Punctuation style is erratic: none, french, english.
3. The README should refer to the blog post but **is not a blog post**. 
4. _Sell_ better the virtual device. It's the beginning of a beautiful thing :smirk_cat:

**Comment by camzeech** [comment]
1. No problemo I'll take care of that.
2. We are talking about Punctuation in the VirtualSensorsActuators.py file, right? I don't think there are punctation issues in the other files.
3. README doesn't look like a blog post to me. Could you clarify ? The blog post is another file called "blog article"
4. Sell better... in the blog post right ?

**Comment by camzeech** [comment]
1. Corrected
2. Corrected
3. README is a README post
4. blog post is called Blog article. Could insert some pictures in it too.

If more is to do, a new issue can be opened
